export const posts = [
	{
	  postId: "1",
	  username: "tushar07",
	  authorImg: "https://via.placeholder.com/150?text=User+Image",
	  time: "1 day ago",
	  contentText: "Exploring the beauty of nature. 🌿",
	  contentImgs: [
		"/post-images/post1-1.jpg",
		"/post-images/post1-2.jpg",
		"/post-images/post1-3.jpg"
	  ],
	  likes: 2435,
	  comments: 345,
	  shares: 150,
	  isLiked: true,
	  location: "Manali, India",
	  hashtags: ["#nature", "#travel", "#photography"],
	},
	{
	  postId: "2",
	  username: "steve_captain",
	  authorImg: "https://via.placeholder.com/150?text=User+Image",
	  time: "2 hours ago",
	  contentText: "Completed my first marathon! 🏃‍♂️🔥",
	  contentImgs: ["/post-images/post2-1.jpg","/post-images/post2-2.jpg"],
	  likes: 984,
	  comments: 47,
	  shares: 20,
	  isLiked: false,
	  location: "New York, USA",
	  hashtags: ["#marathon", "#fitness", "#goalachieved"],
	},
	{
	  postId: "3",
	  username: "lisa_writes",
	  authorImg: "https://via.placeholder.com/150?text=User+Image",
	  time: "5 minutes ago",
	  contentText: "Feeling inspired today. Here's a poem I wrote about life. ✍️✨",
	  contentImgs: [
		"/post-images/post3-1.jpg",
		"/post-images/post3-2.jpg"
		],
	  likes: 202,
	  comments: 35,
	  shares: 10,
	  isLiked: false,
	  location: "",
	  hashtags: ["#poetry", "#inspiration", "#writing"],
	},
	{
	  postId: "4",
	  username: "john_doe",
	  authorImg: "https://via.placeholder.com/150?text=User+Image",
	  time: "3 days ago",
	  contentText: "Throwback to last summer. ☀️🌊",
	  contentImgs: [
		"/post-images/post4-1.jpg",
		"/post-images/post4-2.jpg",
		"/post-images/post4-3.jpg",
	  ],
	  likes: 567,
	  comments: 78,
	  shares: 25,
	  isLiked: true,
	  location: "Miami, USA",
	  hashtags: ["#throwback", "#summer", "#beachlife"],
	},
  ];
  